In [2]:
import numpy as np
import pandas as pd

In [3]:
omdb_initframe = pd.read_csv('E:/greenfox/ProjectPhase/third_week/omdb_datasets/omdb_0to100k.csv', sep=';', encoding='latin-1', low_memory=False)

In [4]:
omdb_initframe.drop(columns=['Unnamed: 0'], inplace = True)
omdb_initframe.set_index(['imdbID'])

,Title,Rated,Released,Runtime,Genre,Director,Language,Country,Awards,imdbVotes,BoxOffice,Website,imdb_Rating,RottenTomatoes_Rating,Metacritic_Rating
imdbID,,,,,,,,,,,,,,,
tt0111161,The Shawshank Redemption,R,14 Oct 1994,142 min,Drama,Frank Darabont,English,USA,Nominated for 7 Oscars. Another 19 wins & 32 n...,"2,045,900",NaN,NaN,2009.03.10,91%,80/100
tt0468569,The Dark Knight,PG-13,18 Jul 2008,152 min,"Action, Crime, Drama, Thriller",Christopher Nolan,"English, Mandarin","USA, UK",Won 2 Oscars. Another 152 wins & 155 nominations.,"2,005,606","$533,316,061",http://thedarkknight.warnerbros.com/,9.0/10,94%,84/100
tt1375666,Inception,PG-13,16 Jul 2010,148 min,"Action, Adventure, Sci-Fi, Thriller",Christopher Nolan,"English, Japanese, French","USA, UK",Won 4 Oscars. Another 152 wins & 204 nominations.,"1,779,523","$292,568,851",http://inceptionmovie.warnerbros.com/,2008.08.10,86%,74/100
tt0137523,Fight Club,R,15 Oct 1999,139 min,Drama,David Fincher,English,"USA, Germany",Nominated for 1 Oscar. Another 10 wins & 34 no...,"1,637,580",NaN,http://www.foxmovies.com/fightclub/,2008.08.10,79%,66/100
tt0110912,Pulp Fiction,R,14 Oct 1994,154 min,"Crime, Drama",Quentin Tarantino,"English, Spanish, French",USA,Won 1 Oscar. Another 62 wins & 69 nominations.,"1,589,700",NaN,NaN,2008.09.10,94%,94/100
tt0109830,Forrest Gump,PG-13,06 Jul 1994,142 min,"Drama, Romance",Robert Zemeckis,English,USA,Won 6 Oscars. Another 40 wins & 67 nominations.,"1,550,175","$330,000,000",http://www.paramount.com/movies/forrest-gump/,2008.08.10,73%,82/100
tt0120737,The Lord of the Rings: The Fellowship of the Ring,PG-13,19.dec.01,178 min,"Adventure, Drama, Fantasy",Peter Jackson,"English, Sindarin","New Zealand, USA",Won 4 Oscars. Another 113 wins & 123 nominations.,"1,466,530","$314,000,000",http://www.lordoftherings.net/film/trilogy/the...,2008.08.10,91%,92/100
tt0133093,The Matrix,R,31 Mar 1999,136 min,"Action, Sci-Fi","Lana Wachowski, Lilly Wachowski",English,USA,Won 4 Oscars. Another 34 wins & 48 nominations.,"1,461,604",NaN,http://www.whatisthematrix.com,2008.07.10,88%,73/100
tt0167260,The Lord of the Rings: The Return of the King,PG-13,17.dec.03,201 min,"Action, Adventure, Drama, Fantasy",Peter Jackson,"English, Quenya, Old English, Sindarin","New Zealand, USA",Won 11 Oscars. Another 197 wins & 122 nominati...,"1,451,338","$364,000,000",http://www.lordoftherings.net/,2008.09.10,93%,94/100
tt0068646,The Godfather,R,24 Mar 1972,175 min,"Crime, Drama",Francis Ford Coppola,"English, Italian, Latin",USA,Won 3 Oscars. Another 24 wins & 28 nominations.,"1,397,893",NaN,http://www.thegodfather.com,2009.02.10,98%,100/100
tt0944947,Game of Thrones,TV-MA,17 Apr 2011,57 min,"Action, Adventure, Drama, Fantasy, Romance",NaN,English,"USA, UK",Won 1 Golden Globe. Another 273 wins & 454 nom...,"1,403,052",NaN,NaN,2009.05.10,NaN,NaN
tt1345836,The Dark Knight Rises,PG-13,20 Jul 2012,164 min,"Action, Thriller",Christopher Nolan,"English, Arabic","UK, USA",Nominated for 1 BAFTA Film Award. Another 38 w...,"1,352,041","$448,130,642",http://www.thedarkknightrises.com/,2008.04.10,87%,78/100
tt0167261,The Lord of the Rings: The Two Towers,PG-13,18.dec.02,179 min,"Adventure, Drama, Fantasy",Peter Jackson,"English, Sindarin, Old English","New Zealand, USA",Won 2 Oscars. Another 118 wins & 137 nominations.,"1,310,858","$339,700,000",http://www.lordoftherings.net/,2008.07.10,95%,87/100
tt0114369,Se7en,R,22 Sep 1995,127 min,"Crime, Drama, Mystery, Thriller",David Fincher,English,USA,Nominated for 1 Oscar. Another 25 wins & 33 no...,"1,251,428",NaN,NaN,2008.06.10,81%,65/100
tt0816692,Interstellar,PG-13,07.nov.14,169 min,"Adventure, Drama, Sci-Fi",Christopher Nolan,English,"USA, UK",Won 1 Oscar. Another 43 wins & 143 nominations.,"1,245,395","$158,737,441",http://www.InterstellarMovie.com/,2008.06.10,72%,74/100
tt0172495,Gladiator,R,05 May 2000,155 min,"Action, Adventure, Drama",Ridley Scott,English,"USA, UK",Won 5 Oscars. Another 53 wins & 101 nominations.,"1,174,472",NaN,http://www.gladiator-thefilm.com,2008.05.10,76%,67/100
tt1853728,Django Unchained,R,25.dec.12,165 min,"Drama, Western",Quentin Tarantino,"English, German, French, Italian",USA,Won 2 Oscars. Another 56 wins & 151 nominations.,"1,171,713","$162,804,648",http://unchainedmovie.com/,2008.04.10,86%,81/100
tt0372784,Batman Begins,PG-13,15 Jun 2005,140 min,"Action, Adventure, Thriller",Christopher Nolan,"English, Urdu, Mandarin","USA, UK",Nominated for 1 Oscar. Another 14 wins & 72 no...,"1,164,146","$204,100,000",http://www.batmanbegins.com/,2008.03.10,84%,70/100
tt0903747,Breaking Bad,TV-MA,20.jan.08,49 min,"Crime, Drama, Thriller",NaN,"English, Spanish",USA,Won 2 Golden Globes. Another 144 wins & 225 no...,"1,145,669",NaN,NaN,2009.05.10,NaN,NaN
tt0848228,The Avengers,PG-13,04 May 2012,143 min,"Action, Adventure, Sci-Fi",Joss Whedon,"English, Russian, Hindi",USA,Nominated for 1 Oscar. Another 38 wins & 79 no...,"1,144,824","$623,279,547",http://marvel.com/avengers_movie,2008.01.10,92%,69/100
tt0102926,The Silence of the Lambs,R,14.febr.91,118 min,"Crime, Drama, Thriller",Jonathan Demme,English,USA,Won 5 Oscars. Another 54 wins & 44 nominations.,"1,094,336",NaN,NaN,2008.06.10,96%,85/100
tt0076759,Star Wars: Episode IV - A New Hope,PG,25 May 1977,121 min,"Action, Adventure, Fantasy, Sci-Fi",George Lucas,English,USA,Won 6 Oscars. Another 50 wins & 28 nominations.,"1,092,532",NaN,http://www.starwars.com/episode-iv/,2008.06.10,93%,90/100
tt0361748,Inglourious Basterds,R,21.aug.09,153 min,"Adventure, Drama, War","Quentin Tarantino, Eli Roth","English, German, French, Italian","Germany, USA",Won 1 Oscar. Another 129 wins & 165 nominations.,"1,086,100","$120,523,073",http://www.inglouriousbasterds-movie.com/,2008.03.10,88%,69/100
tt0120815,Saving Private Ryan,R,24 Jul 1998,169 min,"Drama, War",Steven Spielberg,"English, French, German, Czech",USA,Won 5 Oscars. Another 74 wins & 74 nominations.,"1,076,341",NaN,http://https://www.facebook.com/SavingPrivateR...,2008.06.10,93%,90/100
tt0108052,Schindler's List,R,04.febr.94,195 min,"Biography, Drama, History",Steven Spielberg,"English, Hebrew, German, Polish",USA,Won 7 Oscars. Another 82 wins & 49 nominations.,"1,057,124",NaN,http://www.schindlerslist.com,2008.09.10,97%,93/100
tt0407887,The Departed,R,06 Oct 2006,151 min,"Crime, Drama, Thriller",Martin Scorsese,"English, Cantonese","USA, Hong Kong",Won 4 Oscars. Another 92 wins & 135 nominations.,"1,044,531","$132,300,000",http://www.thedeparted.com/,2008.05.10,90%,85/100
tt0482571,The Prestige,PG-13,20 Oct 2006,130 min,"Drama, Mystery, Sci-Fi, Thriller",Christopher Nolan,English,"USA, UK",Nominated for 2 Oscars. Another 5 wins & 37 no...,"1,036,587","$53,100,000",http://touchstone.movies.go.com/index.html?dli...,2008.05.10,75%,66/100
tt0080684,Star Wars: Episode V - The Empire Strikes Back,PG,20 Jun 1980,124 min,"Action, Adventure, Fantasy, Sci-Fi",Irvin Kershner,English,USA,Won 1 Oscar. Another 21 wins & 19 nominations.,"1,021,079","$4,548,170",http://www.starwars.com/episode-v/,2008.08.10,95%,82/100
tt0499549,Avatar,PG-13,18.dec.09,162 min,"Action, Adventure, Fantasy, Sci-Fi",James Cameron,"English, Spanish","UK, USA",Won 3 Oscars. Another 85 wins & 128 nominations.,"1,021,934","$749,700,000",http://www.avatarmovie.com/,2007.08.10,82%,83/100
tt0209144,Memento,R,25 May 2001,113 min,"Mystery, Thriller",Christopher Nolan,English,USA,Nominated for 2 Oscars. Another 56 wins & 55 n...,"1,007,888","$23,844,220",http://www.otnemem.com,2008.05.10,92%,80/100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tt1999716,Entangled,NaN,25 Oct 2012,30 min,"Comedy, Sci-Fi",Doug Naylor,NaN,NaN,NaN,301,NaN,NaN,2008.03.10,NaN,NaN
tt2089230,Pack Your Lederhosen,TV-MA,29.febr.12,45 min,"Comedy, Crime, Drama",Lisa Marie Gamlem,NaN,NaN,NaN,179,NaN,NaN,2007.08.10,NaN,NaN
tt7020608,School 2017,NaN,01 Jul 2017,NaN,Drama,NaN,Korean,South Korea,NaN,172,NaN,NaN,2007.08.10,NaN,NaN
tt0298452,We,NaN,NaN,27 min,"Documentary, Short",Artavazd Peleshian,Armenian,Soviet Union,NaN,320,NaN,NaN,2007.07.10,NaN,NaN
tt0582489,Sea Bee Jeebies,TV-PG,02.dec.03,21 min,Comedy,Kelsey Grammer,English,USA,NaN,230,NaN,NaN,2007.07.10,NaN,NaN
tt3370324,Soul Mates,NaN,NaN,NaN,"Comedy, Fantasy",NaN,English,Australia,1 nomination.,287,NaN,NaN,2007.07.10,NaN,NaN
tt4675114,Episode #1.3,NaN,10.jan.16,60 min,"Crime, Drama, Thriller",Baldvin ZophonÃ­asson,NaN,NaN,NaN,56,NaN,NaN,8.0/10,NaN,NaN
tt0539453,The Last Temptation of Christy,TV-PG,19.febr.06,42 min,"Drama, Fantasy, Mystery",John T. Kretchmer,English,USA,NaN,217,NaN,NaN,2007.06.10,NaN,NaN
tt0582458,Moons Over Seattle,TV-PG,21 May 2002,60 min,Comedy,Sheldon Epps,English,USA,NaN,229,NaN,NaN,2007.05.10,NaN,NaN
tt0642440,You Gotta Know When to Hold Them: Part 1,TV-PG,11.febr.90,22 min,Comedy,Gerry Cohen,English,USA,NaN,204,NaN,NaN,2006.08.10,NaN,NaN
tt0655410,Diabolik,TV-14,08.aug.99,97 min,"Comedy, Sci-Fi",Kevin Murphy,NaN,NaN,NaN,185,NaN,NaN,2008.08.10,NaN,NaN
tt0688816,Into That Good Night: Part 2,TV-PG,20 May 1997,22 min,"Comedy, Drama",Gary Halvorson,English,USA,NaN,206,NaN,NaN,2007.09.10,NaN,NaN
tt6135658,Ke Ku 'Ana,TV-14,21 Oct 2016,41 min,"Action, Crime, Drama",Bobby Roth,English,USA,NaN,296,NaN,NaN,2007.05.10,NaN,NaN
tt0069068,Pechki-lavochki,NaN,02 Apr 1972,90 min,Comedy,Vasiliy Shukshin,Russian,Soviet Union,NaN,248,NaN,NaN,2007.05.10,NaN,NaN
tt0069936,Blossoms in Autumn,NaN,21 Jun 1973,122 min,"Drama, Romance",Matjaz Klopcic,Slovenian,Yugoslavia,2 wins.,294,NaN,NaN,2007.05.10,NaN,NaN
tt2281201,"Doin' It in the Park: Pick-Up Basketball, NYC",NaN,17 Jun 2012,83 min,"Documentary, History, Sport","Kevin Couliau, Bobbito Garcia",English,"USA, France",NaN,313,NaN,http://www.facebook.com/doinitinthepark,2007.05.10,75%,71/100
tt2393324,Icche,NaN,15 Jul 2011,132 min,Drama,"Shibprasad Mukhopadhyay, Nandita Roy",Bengali,India,NaN,286,NaN,NaN,2007.05.10,NaN,NaN
tt2719370,Bet Raise Fold,TV-14,30 Jun 2013,100 min,"Documentary, Crime, Drama",Ryan Firpo,English,"USA, Canada",NaN,295,NaN,http://facebook.com/betraisefoldmovie,2007.06.10,NaN,NaN
tt7009266,"Celtics/Lakers: Best of Enemies, Part 2",TV-G,14 Jun 2017,51 min,"Documentary, Biography, History",Jim Podhoretz,NaN,NaN,NaN,222,NaN,NaN,7.0/10,NaN,NaN
tt0193373,The Last Act,NaN,NaN,105 min,"Crime, Drama, Mystery",Varuzh Karim-Masihi,Persian,Iran,NaN,269,NaN,NaN,2007.06.10,NaN,NaN
tt6627134,Disgraced,TV-14,10 Mar 2017,102 min,"Documentary, Crime, Sport",Pat Kondelis,English,USA,1 nomination.,306,NaN,NaN,2007.04.10,NaN,NaN
tt6722630,U2: Where the Streets Have No Name,NaN,01 Sep 1987,7 min,"Short, Music",Meiert Avis,English,USA,NaN,185,NaN,NaN,2006.08.10,NaN,NaN
tt7293016,The Murder of Laci Peterson,NaN,15.aug.17,43 min,"Documentary, Crime",NaN,English,USA,NaN,187,NaN,NaN,2007.04.10,NaN,NaN
tt0304782,Terrorised by Teens: The Jonathan Wamback Story,NaN,02 Jul 2005,120 min,Drama,John L'Ecuyer,English,Canada,6 nominations.,305,NaN,NaN,2007.03.10,NaN,NaN
tt1942314,Salon of the Dead,TV-14,16 Apr 2012,42 min,"Drama, Romance",Norman Buckley,English,USA,NaN,285,NaN,NaN,2007.03.10,NaN,NaN
tt2393117,Death and the Divas,NaN,02.jan.13,89 min,"Crime, Drama, Mystery",Nicholas Laughland,English,UK,NaN,242,NaN,NaN,2007.01.10,NaN,NaN
tt4695462,Salut d'Amour,NaN,09 Apr 2015,112 min,"Drama, Romance",Je-kyu Kang,Korean,South Korea,1 nomination.,267,NaN,NaN,2007.02.10,NaN,NaN
tt8889956,Luke,NaN,07.nov.18,42 min,"Crime, Drama, Mystery, Thriller",Joe Mantegna,English,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tt0300533,Survivor Series,TV-14,18.nov.01,180 min,Sport,Kevin Dunn,English,USA,NaN,301,NaN,NaN,2007.03.10,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
omdb_initframe['Runtime'] = omdb_initframe['Runtime'].str.extract(r'(\d+)')
omdb_initframe['Runtime'] = omdb_initframe['Runtime'].astype('float64')

In [6]:
omdb_initframe['Director'].replace({np.nan}, {''}, inplace=True)

# Removing commas from imdbVotes column

In [7]:
omdb_initframe['imdbVotes'].replace(r',', r'', regex=True, inplace = True)
omdb_initframe['imdbVotes']=omdb_initframe['imdbVotes'].astype('float64')

# Remove non-digit characters from Boxoffice column

In [8]:
omdb_initframe['BoxOffice'] = omdb_initframe['BoxOffice'].str[1:]

In [9]:
omdb_initframe.at[75940, 'BoxOffice'] = 25700

In [10]:
omdb_initframe['BoxOffice'].replace(r',' , r'', regex=True, inplace = True)
omdb_initframe['BoxOffice'] = omdb_initframe['BoxOffice'].astype('float64')

# Convert imdb_Rating values between 0-1 format

In [11]:
omdb_initframe['imdb_Rating'] = omdb_initframe['imdb_Rating'].str.extract(r'(^\d?\.\d)')
omdb_initframe['imdb_Rating'] = omdb_initframe['imdb_Rating'].astype('float64')
omdb_initframe['imdb_Rating'] = omdb_initframe['imdb_Rating']/10

# Convert RottenTomatoes_Rating values between 0-1 format

In [12]:
omdb_initframe['RottenTomatoes_Rating'] = omdb_initframe['RottenTomatoes_Rating'].str.extract(r'(^\d+)')
omdb_initframe['RottenTomatoes_Rating'] = omdb_initframe['RottenTomatoes_Rating'].astype('float64')
omdb_initframe['RottenTomatoes_Rating'] = omdb_initframe['RottenTomatoes_Rating']/100

# Convert Metacritic_Rating values between 0-1 format

In [13]:
omdb_initframe['Metacritic_Rating'] = omdb_initframe['Metacritic_Rating'].str.extract(r'(^\d+)')
omdb_initframe['Metacritic_Rating'] = omdb_initframe['Metacritic_Rating'].astype('float64')
omdb_initframe['Metacritic_Rating'] = omdb_initframe['Metacritic_Rating']/100

In [14]:
omdb_initframe['Website'].replace(np.nan, '', inplace = True)

In [15]:
Oscar_winner = omdb_initframe['Awards'].str.extract(r'(Won \d+ O\w+)', expand=False)

In [16]:
Oscar_nominated = omdb_initframe['Awards'].str.extract(r'(^\w+ \w+ \d+ [O|G]\w+)', expand=False)

In [17]:
omdb_initframe.insert(omdb_initframe.columns.get_loc('Awards')+1, 'Oscar_winner', Oscar_winner)

In [18]:
omdb_initframe.insert(omdb_initframe.columns.get_loc('Awards')+2, 'Award_nomination', Oscar_nominated)

In [19]:
omdb_initframe['Oscar_winner'].replace(np.nan, '', inplace = True)
omdb_initframe['Award_nomination'].replace(np.nan, '', inplace = True)

In [25]:
omdb_initframe.loc[omdb_initframe['Title'].isnull()]

,imdbID,Title,Rated,Released,Runtime,Genre,Director,Language,Country,Awards,Oscar_winner,Award_nomination,imdbVotes,BoxOffice,Website,imdb_Rating,RottenTomatoes_Rating,Metacritic_Rating
99996,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,,,NaN,NaN,,NaN,NaN,NaN

In [28]:
omdb_initframe.drop([99996], inplace = True)

KeyError: '[99996] not found in axis'

In [29]:
omdb_initframe.loc[omdb_initframe['Title'].isnull()]

Empty DataFrame
Columns: [imdbID, Title, Rated, Released, Runtime, Genre, Director, Language, Country, Awards, Oscar_winner, Award_nomination, imdbVotes, BoxOffice, Website, imdb_Rating, RottenTomatoes_Rating, Metacritic_Rating]
Index: []

In [30]:
omdb_initframe.to_csv('omdb_clean.csv')